name: CI

on:
  push:
    paths-ignore:
      - 'Documentation/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'README.md'

jobs:
  build:
    name: Test with PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -s composerInstall -p ${{ matrix.php-versions }}
      - name: Run PHP linter
        run: |
          ./Build/Scripts/runTests.sh -s lint -p ${{ matrix.php-versions }}
      - name: Run unit tests
        run: |
          ./Build/Scripts/runTests.sh -s unit -p ${{ matrix.php-versions }}
      - name: Run acceptance tests
        run: |
          ./Build/Scripts/runTests.sh -s acceptance -p ${{ matrix.php-versions }}
  sonar-cloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
